babyBradyNinja/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='homepage.html'), name='homepage'),
    url(r'^polls/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^(?P<question_id>[0-9]+)/$', views.details, name='details'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    publication_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    class Meta:
        ordering = ['choice_text']

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    number_of_votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices = question.choice_set.all()
    total_votes = 0
    boy_votes = 0
    girl_votes = 0
    for choice in choices:
        if choice.choice_text == 'boy':
            boy_votes = choice.number_of_votes
        elif choice.choice_text == 'girl':
            girl_votes = choice.number_of_votes

        total_votes += choice.number_of_votes
    if total_votes != 0:
        boy_percent = int(boy_votes / total_votes * 100)
        girl_percent = int(girl_votes / total_votes * 100)
    else:
        boy_percent = 0
        girl_percent = 0

    return render(request, 'polls/results.html', {
        'question': question,
        'boy_votes': boy_votes,
        'girl_votes': girl_votes,
        'boy_percent': boy_percent,
        'girl_percent': girl_percent
    })


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice!",
        })
    else:
        selected_choice.number_of_votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

babyBradyNinja/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />

    <title>Baby Brady Ninja</title>
</head>
<body>
    <div class="container">
        <div class="top-half">
            <div class="boy">Is it a boy?</div>
        </div>
        <div class="separator"></div>
        <a href="/polls/1" class="greeting-section center-page">
            <div class="greeting">
                <div class="greeting-title">
                    <div class="heading">Baby Stephenson</div>
                    <div>Coming July 2017</div>
                    <div class="click-me">Click Here!</div>
                </div>
            </div>
        </a>
        <div class="bottom-half">
            <div class="girl">Is it a girl?</div>
        </div>
    </div>
</body>
</html>

polls/templates/polls/details.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'details.css' %}" />
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />

<title>Baby Brady Ninja - Cast Your Vote!</title>

<div class="gender-title"><h1>Cast Your Vote!</h1></div>

<form class="vote-form" action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <div class="gender-container">
        {% for choice in question.choice_set.all %}
            <div class="{{ choice.choice_text }}-container">
                <div class="{{ choice.choice_text }}-helper">Select {{ choice.choice_text | capfirst }}!</div>
                <input class="{{ choice.choice_text }}-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                <label class="{{ choice.choice_text }}-label" for="choice{{ forloop.counter }}"></label>
            </div>
        {% endfor %}
    </div>
    {% if error_message %}
        <div class="error-message">{{ error_message }}</div>
    {% endif %}
    <input class="vote-button" type="submit" value="Submit Vote">
</form>

polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'results.css' %}" />
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />

<title>Baby Brady Ninja - Total Votes</title>

<div class="title"><h1>Total Votes</h1></div>
<div class="graphs-container">
    <div class="boy-graph-container">
        {% if boy_percent > 0 %}
            <div class="boy-graph" style="height: {{ boy_percent }}%">
                <div class="votes">{{ boy_votes }} Votes {{ boy_percent }}%</div>
            </div>
        {% else %}
            <div class="boy-graph" style="height: 5%"></div>
            <div class="boy-zero-votes">0 Votes 0%</div>
        {% endif %}
    </div>
    <div class="girl-graph-container">
        {% if girl_percent > 0 %}
            <div class="girl-graph" style="height: {{ girl_percent }}%">
                <div class="votes">{{ girl_votes }} Votes {{ girl_percent }}%</div>
            </div>
        {% else %}
            <div class="girl-graph" style="height: 5%"></div>
            <div class="girl-zero-votes">0 Votes 0%</div>
        {% endif %}
    </div>
</div>

polls/templates/polls/vote.html
{{ question.question_text }}